import localFont from "next/font/local";
import "./globals.css";
import '@mantine/core/styles.css';
import Header from "@/components/applayout/header"; // Certifique-se que o caminho esteja correto
import { Container, Group, Button, MantineProvider } from '@mantine/core';
import Link from 'next/link';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Metadados e links de fontes podem ser colocados aqui */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider>
          <Container>
            <Group position="center" spacing="xl">
              <Link href="/perfil_cliente">
                <Button variant="light">Perfil do Cliente</Button>
              </Link>
              <Link href="/">
                <Button variant="light">Catálogo de Veículos</Button>
              </Link>
              <Link href="/cadastro_cliente">
                <Button variant="light">Cadastro de Cliente</Button>
              </Link>
            </Group>
          </Container>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
